version: "3"
services:
  backend:
    container_name: "backend"
    volumes:
      - ./backend:/code
    tty: true
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  frontend:
    container_name: "frontend"
    volumes:
      - .:/code
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile