version: "3"
services:
  backend:
    container_name: "backend"
    volumes:
      - ./backend:/code
    tty: true
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000