version: "3"
services:
  backend:
    container_name: "backend"
    volumes:
      - ./backend:/backend
    tty: true
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  frontend:
    container_name: "frontend"
    volumes:
      - ./frontend:/frontend
    tty: true
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080